### ISSUE TITLE
replace server with 2 workspaces

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/reactjs-boilerplate#10]
- [x] server that only serves the bundle (with fancy stuff like chunk on demand streaming in production env)
- ~~backend stub with the current rest api example/stub~~

**Comment by maddrag0n** [comment]
express vs hapi?

**Comment by zGrav** [comment]
Will hopefully pick this up, this week.

I'm down for a hapi branch if you're cool with it.

**Comment by zGrav** [comment]
PR #18 built for this issue.
