### ISSUE TITLE
add auto prefixing for react inline styles to web pack

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/reactjs-boilerplate#13]
[postcss-js](https://yarnpkg.com/en/package/postcss-js)

**Comment by maddrag0n** [comment]
we might have to write a webpack-loader for this first

**Comment by zGrav** [comment]
https://github.com/postcss/postcss-loader

does this help @maddrag0n ?

**Comment by zGrav** [comment]
since we're already using postcss-loader in our package.json, what do we need here exactly?

**Comment by maddrag0n** [comment]
auto prefixing for react inline styles

**Comment by zGrav** [comment]
as in the vendor stuff?

```
-webkit
-o
```

If so, https://github.com/FormidableLabs/radium this could help maybe 🤔

**Comment by maddrag0n** [comment]
radium is a different approach

**Comment by maddrag0n** [comment]
I was more thinking looking at react element props for style and autoprefixing these

**Comment by maddrag0n** [comment]
this is blocked until we have released a react-autoprefixer-webpack-plugin

**Comment by maddrag0n** [comment]
closed because too much effort and too little impact for now
