### ISSUE TITLE
add NASA control center to web pack

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/reactjs-boilerplate#14]
blocked by https://github.com/bitchcraft/reactjs-boilerplate/issues/10

[webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard)

**Comment by zGrav** [comment]
Nodemon currently has issues with libs used in webpack-dashboard

**Comment by maddrag0n** [comment]
did you open an issue for webpack-dashboard?

**Comment by zGrav** [comment]
https://github.com/FormidableLabs/webpack-dashboard/issues/223

already known

**Comment by maddrag0n** [comment]
this is gonna be a non-issue for us as soon as we split the server (https://github.com/bitchcraft/reactjs-boilerplate/issues/10)

**Comment by zGrav** [comment]
found a workaround, pushed.
