### ISSUE TITLE
proper api server logging

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/reactjs-boilerplate#16]
Related to #10 

* proper request logging with log file rotation with Morgan and Winston
* http://tostring.it/2014/06/23/advanced-logging-with-nodejs/

**Comment by zGrav** [comment]
I may pick this up, unless you want @LemonaOna or @cvey to tackle this one 🤘

**Comment by zGrav** [comment]
pushed into #18

**Comment by zGrav** [comment]
Closed #16
