### ISSUE TITLE
update to material-ui@next (1.0.0-beta.38)

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/reactjs-boilerplate#19]
# tasks

- [x] update deps
- [x] migrate components

# why?

material-ui@^0.20.0 still depends on react-transition-group@^1.0.0 which can cause console spam when using react@^14.0.0 (because of adding unsupported props to HTMLElements). This can lead to broken transition behavior (e. g. reproducible when using react components that use material-ui dialogs wrapped in a ngReact directive)

material-ui@next uses react-transition-group@^2.0.0 where that is fixed.

**Comment by zGrav** [comment]
I'm on this tomorrow.

**Comment by zGrav** [comment]
PR #20 submitted for this issue.

**Comment by fw-work** [comment]
I want to fuck you

**Comment by zGrav** [comment]
Closed #19
