### ISSUE TITLE
Fix styleguide

### ISSUE THREAD

**Issue by thiemok** [bitchcraft/reactjs-boilerplate#24]
styleguidist currently fails to compile with error:
`Module not found: Can't resolve 'rsg-components/Wrapper/Wrapper' in '/home/thiemokrause/Development/reactjs-boilerplate/node_modules/react-styleguidist/lib/rsg-components/Wrapper'`

**Comment by zGrav** [comment]
Opened Issue https://github.com/styleguidist/react-styleguidist/issues/1051

**Comment by zGrav** [comment]
Fixed
